package com.j.s.galley.program;

import org.springframework.data.annotation.Id;
import org.springframework.stereotype.Repository;

import javax.persistence.*;
import java.util.Set;

//DB Actor Class
@Entity
@Table(name="actor")
public class Actor {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    int actor_id; //no need to be in the constructor because it is a pk and is autogenerated
    String first_name;
    String last_name;

    public Actor(String first_name, String last_name)
    {
        this.first_name = first_name;
        this.last_name = last_name;
    }
    //special constructor
    public Actor(){}

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String toString()
    {
        return first_name + " " + last_name;
    }
}
